title: "Dust et Lumina"
description: "...descriptions..."

# Project Settings
# If your site is at username.github.io/my-world/, set baseurl to "/my-world"
baseurl: "/Dust-et-Lumina"
url: "https://dim-42.github.io" 

# Build Settings
markdown: kramdown
## theme: minima # You can change this later when we do styling
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    
# Folder Exclusion
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections_dir: _lore

collections:
  organizations:
    output: true
    permalink: /organizations/:path/
    display_name: [Faction, 组织势力]
  characters:
    output: true
    permalink: /characters/:path/
    display_name: [Personnel,人物档案]
  regions:
    output: true
    permalink: /regions/:path/
    display_name: [Galactic Atlas,世界地理]
  stories:
    output: true
    permalink: /stories/:path/
    display_name: [Record,故事]
  culture:
    output: true
    permalink: /culture/:path/
    display_name: [Encyclopedia,百科]
  histories:
    output: true
    permalink: /histories/:path/
    display_name: [History,历史]
    
navigation:
  - title: "Terminal"
    url: /
  - title: "Faction"
    url: /organizations/
  - title: "Personnel"
    url: /characters/
  - title: "Atlas"
    url: /regions/
  - title: "Encyclopedia"
    url: /culture/
  - title: "History"
    url: /histories/
  - title: "Record"
    url: /stories/
  - title: "About"
    url: /about/

