title: "Dust et Lumina"
description: "...descriptions..."

# Project Settings
# If your site is at username.github.io/my-world/, set baseurl to "/my-world"
baseurl: "/Dust-et-Lumina"
url: "https://dim-42.github.io" 

# Build Settings
markdown: kramdown
## theme: minima # You can change this later when we do styling
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Folder Exclusion
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections_dir: _lore

collections:
  concepts:
    output: true
    permalink: /concepts/:path/
  characters:
    output: true
    permalink: /characters/:path/
  regions:
    output: true
    permalink: /regions/:path/

navigation:
  - title: "Terminal"
    url: /
  - title: "Basics"
    url: /basics/
  - title: "Personnel"
    url: /characters/
  - title: "Regions"
    url: /regions/